---
title: "1.4 Github"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
```

```{r libraries}
library(tidyverse)

health_full <- read_csv("https://chronicdata.cdc.gov/api/views/6vp6-wxuq/rows.csv?accessType=DOWNLOAD")

pge_19_q1_elec <- read_csv("PGE_2019_Q1_ElectricUsageByZip.csv")
```

```{r}
year <- 2019
quarters <- 1:4
type <- "Electric"

pge_19_elec <- NULL

for(quarter in quarters) {
  filename <- paste0(
    "PGE_",
    year,
    "_Q",
    quarter,
    "_",
    type,
    "UsageByZip.csv"
    )
  print(filename)
  temp = read_csv(filename)
  pge_19_elec <- rbind(pge_19_elec,temp)
  saveRDS(pge_19_elec, "pge_19_elec.rds")
}

```
```{r}
pge_filter <- 
  filter(
    pge_19_elec,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  )
names(pge_filter)
```
```{r}
pge_final <-
  pge_19_elec %>%
  filter(
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  ) %>%
  select(
    -YEAR,
    -COMBINED,
    -AVERAGEKWH
  ) %>%
  group_by(
    MONTH,
    CUSTOMERCLASS
  ) %>%
  summarize(
    TOTALKWH =
      sum(
        TOTALKWH,
        na.rm = T
      ),
    TOTALCUSTOMERS = 
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      )
  ) %>%
  mutate(
    AVERAGEKWH = TOTALKWH/TOTALCUSTOMERS
  )
```
```{r}
library(plotly)

pge_chart <-
  pge_final %>% 
  ggplot() +
  geom_bar(
    aes(
      x = MONTH %>% factor(),
      y = TOTALKWH,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "kWh",
    title = "PG&E Territory Monthly Electricity Usage, 2019",
    fill = "Electricity Type"
  )

pge_chart %>% 
  ggplotly() %>% 
  config(displayModeBar = F)

plot_ly() %>% 
  add_trace(
    data = pge_final %>% filter(CUSTOMERCLASS == "Elec- Commercial"),
    x = ~MONTH %>% factor(),
    y = ~TOTALKWH,
    type = "bar",
    name = "Residential"
  ) %>% 
  add_trace(
    data = pge_final %>% filter(CUSTOMERCLASS == "Elec- Commercial"),
    x = ~MONTH %>% factor(),
    y = ~TOTALKWH,
    type = "bar",
    name = "Commercial"
  ) %>% 
  layout(
    xaxis = list(
      title = "Month",
      fixedrange = T
    ),
    yaxis = list(
      title = "kWh",
      fixedrange = T
    ),
    barmode = "stack",
    legend = list(title = list(text = "Electricity Type"))
  ) %>% 
  config(displayModeBar = F)
```
```{r}
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)

ca_counties <- counties("CA", cb = T, progress_bar = F)
# st_crs(ca_counties)
# ggplot(ca_counties) + geom_sf()
# leaflet() %>% 
#   addTiles() %>% 
#   addPolygons(
#     data = ca_counties %>% 
#       st_transform(4326)
#   ) %>%
#   addMarkers(
#     data = ca_counties %>% 
#       st_centroid() %>%
#       st_transform(4326)
#   )
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )
bay_counties <-
  ca_counties %>%
  filter(NAME %in% bay_county_names)

ca_cities <- places("CA", cb = T, progress_bar = F)
bay_cities <- ca_cities[bay_counties, ]

bay_cities_within <-
  ca_cities %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_cities %>% select(GEOID)) %>% 
  st_as_sf()

bay_cbgs <- 
  bay_county_names %>% 
  map_dfr(function(county) {
    block_groups("CA", county, cb = T, progress_bar = F)
  })
bay_cbgs_clip <- st_read("https://opendata.arcgis.com/datasets/037fc1597b5a4c6994b89c46a8fb4f06_0.geojson")
ggplot(bay_cbgs_clip) + geom_sf()
# leaflet() %>%
#   addTiles() %>%
#   addPolygons(
#     data = bay_cbgs %>% st_transform(4326),
#     fill = F,
#     weight = 2,
#     color = "purple"
#   ) %>%
#   addPolygons(
#     data = bay_counties %>% 
#       st_transform(4326),
#     fill = F,
#     weight = 2
#   ) %>%
#   addPolygons(
#     data = bay_cities %>% 
#       filter(!GEOID %in% bay_cities_within$GEOID) %>% 
#       st_transform(4326),
#     color = "red"
#   ) %>% 
#   addPolygons(
#     data = bay_cities_within %>% 
#       st_transform(4326),
#     color = "green"
#   )

usa_zips <- 
  zctas(cb = T, progress_bar = F)

bay_zips <- 
  usa_zips %>%
  st_centroid() %>%
  .[bay_counties, ] %>%
  st_set_geometry(NULL) %>%
  left_join(usa_zips %>% select(GEOID10)) %>%
  st_as_sf()

pge_19_res_elec <-
  pge_19_elec %>%
  filter(CUSTOMERCLASS == "Elec- Residential") %>% 
  mutate(
    ZIPCODE = ZIPCODE %>% as.character()
  ) %>% 
  group_by(ZIPCODE) %>% 
  summarize(
    TOTALKWH = sum(TOTALKWH, na.rm = T)
  ) %>% 
  left_join(
    bay_zips %>% select(GEOID10),
    by = c("ZIPCODE" = "GEOID10")
  ) %>% 
  st_as_sf() %>% 
  st_transform(4326)

res_pal <- colorNumeric(
  palette = "Oranges",
  domain = 
    pge_19_res_elec$TOTALKWH
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = pge_19_res_elec,
    fillColor = ~res_pal(TOTALKWH),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKWH), 
      " kWh total in ",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = pge_19_res_elec,
    pal = res_pal,
    values = ~TOTALKWH,
    title = "Total Residential<br>kWh, 2019"
  )
```
```{r}
ca_tracts <- tracts("CA", cb = T, progress_bar = F)
health_ca <- health_full %>% filter(StateAbbr == "CA")

bay_phys_health_17 <-
  health_ca %>% 
  filter(!is.na(TractFIPS)) %>% 
  filter(MeasureId == "PHLTH") %>% 
  filter(!is.na(Data_Value)) %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("TractFIPS" = "GEOID")
  ) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("TractFIPS" = "GEOID")
  ) %>% 
  st_as_sf()

health_pal <- colorNumeric(
  palette = "Purples",
  domain = 
    bay_phys_health_17$Data_Value
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = bay_phys_health_17,
    fillColor = ~health_pal(Data_Value),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(Data_Value), 
      "% in ",
      TractFIPS
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = bay_phys_health_17,
    pal = health_pal,
    values = ~Data_Value,
    title = "Physical health<br>not good for 14+ days<br>among adults aged<br>18+ years, 2019"
  )
```



