---
title: "monte_carlo"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```
```{r}
library(censusapi)
library(tidyverse)
Sys.setenv(CENSUS_KEY="c92c3c586ec2640e86f9d2e8d8b09b5a75f4ea16")
```
```{r}
acs_vars_2018_5yr <-
  listCensusMetadata(
    name = "2018/acs/acs5",
    type = "variables"
  )
income_19_summary <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:001,013,041,055,075,081,085,095,097",
    regionin = "state:06",
    vars = c("group(B19001)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>% 
  group_by(variable) %>% 
  summarize(estimate = sum(estimate)) %>% 
  left_join(
    acs_vars_2018_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable)

income_19_summary

```
```{r}
income_tiers <- 
  data.frame(
    lower_end = c(NA, 0, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000, 60000, 75000, 100000, 125000, 150000, 200000),
    width = c(NA, 10000, rep(5000, 8), 10000, 15000, rep(25000, 3), 50000, NA)
  )
total <- income_19_summary$estimate[1]
row <- 2 
cumulative <- income_19_summary$estimate[row]
proportion <- cumulative/total
while (proportion < 0.5) {
  cumulative_lag <- cumulative
  row <- row + 1
  cumulative <- cumulative + income_19_summary$estimate[row]
  proportion <- cumulative/total
}
median <- 
  income_tiers$lower_end[row] + 
  (total/2 - cumulative_lag) /
  income_19_summary$estimate[row] *
  income_tiers$width[row]
prettyNum(round(median), ",")
```
```{r}
income_19_summary_moe <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:001,013,041,055,075,081,085,095,097",
    regionin = "state:06",
    vars = c("group(B19001)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","E"))) %>%
  pivot_longer(
    ends_with(c("M")),
    names_to = "variable",
    values_to = "estimate"
  ) %>% 
  group_by(variable) %>% 
  summarize(estimate = sqrt(sum(estimate^2)))

income_19_summary_montecarlo <-
  map2(
    income_19_summary$estimate,
    income_19_summary_moe$estimate/1.645,
    function(x,y) {rnorm(10000, x, y)}
  ) %>%
 transpose()

```
```{r}
montecarlo_result <-
  income_19_summary_montecarlo %>% 
  map(function(income){
    
    income <- income %>% unlist()
    total <- income[1]
    row <- 2 
    cumulative <- income[row]
    proportion <- cumulative/total
      
    while (proportion < 0.5) {
      cumulative_lag <- cumulative
      row <- row + 1
      cumulative <- cumulative + income[row]
      proportion <- cumulative/total
    }
      
    median <- 
      income_tiers$lower_end[row] + 
      (total/2 - cumulative_lag) /
      income[row] *
      income_tiers$width[row]
    
  }) %>% 
  unlist()

upper <- mean(montecarlo_result) + 1.645*sd(montecarlo_result)
lower <- mean(montecarlo_result) - 1.645*sd(montecarlo_result)

ggplot() + 
  geom_histogram(
    aes(montecarlo_result)
  ) + 
  geom_vline(
    aes(
      xintercept = mean(montecarlo_result)
    ), 
    colour = "red"
  ) + 
  geom_vline(
    aes(
      xintercept = lower
    ), 
    colour = "red"
  ) + 
  geom_vline(
    aes(
      xintercept = upper
    ), 
    colour = "red"
  ) +
  labs(
    x = "Median Household Income ($)",
    y = "# of Simulations",
    title = "Monte Carlo simulation, Bay Area households"
  )
```


